// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:49954998858:web:f19fbed63f46ec858af4b3',
    messagingSenderId: '49954998858',
    projectId: 'oauth-dadm-2025',
    authDomain: 'oauth-dadm-2025.firebaseapp.com',
    storageBucket: 'oauth-dadm-2025.firebasestorage.app',
    measurementId: 'G-C7SC75NHCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:49954998858:android:4b05aaed731fe05a8af4b3',
    messagingSenderId: '49954998858',
    projectId: 'oauth-dadm-2025',
    storageBucket: 'oauth-dadm-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:49954998858:ios:2aab648c830982b88af4b3',
    messagingSenderId: '49954998858',
    projectId: 'oauth-dadm-2025',
    storageBucket: 'oauth-dadm-2025.firebasestorage.app',
    androidClientId: '49954998858-2nrnm91e4mi3ufdaejsuf9fiovg06ki3.apps.googleusercontent.com',
    iosClientId: '49954998858-i485na9a0h4gdeeth2pjouo1l3efseh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reto12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:49954998858:ios:2aab648c830982b88af4b3',
    messagingSenderId: '49954998858',
    projectId: 'oauth-dadm-2025',
    storageBucket: 'oauth-dadm-2025.firebasestorage.app',
    androidClientId: '49954998858-2nrnm91e4mi3ufdaejsuf9fiovg06ki3.apps.googleusercontent.com',
    iosClientId: '49954998858-i485na9a0h4gdeeth2pjouo1l3efseh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reto12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:49954998858:web:ce19c619c0546a138af4b3',
    messagingSenderId: '49954998858',
    projectId: 'oauth-dadm-2025',
    authDomain: 'oauth-dadm-2025.firebaseapp.com',
    storageBucket: 'oauth-dadm-2025.firebasestorage.app',
    measurementId: 'G-MY9BQS7R4N',
  );
}
